config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :schedules
	root 'schedules#index'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
			 :recoverable, :rememberable, :trackable, :validatable
	
	has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	
	def index
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  	before_action :set_schedule, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show] 

	respond_to :html

	def index
		@schedules = Schedule.all
		respond_with(@schedules)
	end

	def show
		respond_with(@schedule)
	end

	def new
		@schedule = current_user.schedules.build
		respond_with(@schedule)
	end

	def edit
	end

	def create
		@schedule = current_user.schedules.build(schedule_params)
		@schedule.save
		respond_with(@schedule)
	end

	def update
		@schedule.update(schedule_params)
		respond_with(@schedule)
	end

	def destroy
		@schedule.destroy
		respond_with(@schedule)
	end

	private
		def set_schedule
			@schedule = Schedule.find(params[:id])
		end

		def schedule_params
			params.require(:schedule).permit(:gametime, :hteam, :ateam, :division_type)
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
    	<div class="navbar-header">
			<!-- creates menu button on mobile view -->
      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#stocks-collapse">
        		<span class="sr-only">Toggle navigation</span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
      	</button>
			<%= link_to "GG Arena Soccer", root_path, class:"navbar-brand" %>
    	</div>

    	<div class="collapse navbar-collapse" id="stocks-collapse">
      	<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="nav-links w-outline"><%= link_to "Schedule" %></li>
					<li class="nav-links"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li class="nav-links w-outline"><%= link_to "Schedule" %></li>
				<% end %>
      	</ul>
    	</div>
	</div><!-- /container -->
</nav><!-- /nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ggarenasoccer</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	
	<body>

		<%= render 'layouts/navbar' %>

		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-warning") %>
			<% end %>
			
			<%= yield %>
		</div>

	</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
	<% if @schedule.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

			<ul>
				<% @schedule.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
  	<% end %>

	<div class="field">
		<%= f.label "Game Time" %><br>
		<%= f.text_field :gametime %>
	</div>
	<div class="field">
		 <%= f.label "Home Team" %><br>
		 <%= f.text_field :hteam %>
	</div>
	<div class="field">
		 <%= f.label "Away Team" %><br>
		 <%= f.text_field :ateam %>
	</div>
	<div class="field">
		 <%= f.label "Division" %><br>
		 <%= f.select(:division_type, options_for_select([['GU11', 'GU11'], ['GU9', 'GU9'], ['BU11', 'BU11'], ['BU12', 'BU12']])) %>
	</div><br>
	<div class="actions">
	 	<%= f.submit %>
	</div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61080402-1', 'auto');
  ga('send', 'pageview');

</script>

<div class="jumbotron main-jumbo">
	<h1 class="center">Schedule &amp; Results</h1>
	<h2 class="center date-color"><em>March 22, 2015</em></h2>
</div>

<!-- ********************************* U8 ************************************************************* -->
<div class="panel panel-success">
	<div class="panel-heading">
		<h3 class="center division-heading"><strong><em>Girls U11</em></strong></h3>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th>Time</th>
						<th>Home</th>
						<th>Away</th>
					</tr>
				</thead>

  				<tbody>
					<% @schedules.each do |schedule| %>
						<% if schedule.division_type == 'GU11' %>
							<tr>
								<td><%= schedule.gametime %></td>
								<td><%= schedule.hteam %></td>
								<td><%= schedule.ateam %></td>
								<% if schedule.user == current_user %>
									<td><%= link_to 'Show', schedule, class:"btn btn-success btn-xs" %> 
									<%= link_to 'Edit', edit_schedule_path(schedule), class:"btn btn-warning btn-xs" %> 
									<%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn 	btn-danger btn-xs" %></td>
								<% else %>

								<% end %>
							</tr>
						<% end %>
					<% end %>
  				</tbody>
			</table>
		</div>
	</div>
</div>

<!-- ********************************* U11 ************************************************************* -->
<div class="panel panel-success">
	<div class="panel-heading">
		<h3 class="center division-heading"><strong><em>Boys U11</em></strong></h3>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th>Time</th>
						<th>Home</th>
						<th>Away</th>
					</tr>
				</thead>

				<tbody>
					<% @schedules.each do |schedule| %>
						<% if schedule.division_type == 'BU11' %>
							<tr>
								<td><%= schedule.gametime %></td>
								<td><%= schedule.hteam %></td>
								<td><%= schedule.ateam %></td>
								<% if schedule.user == current_user %>
									<td><%= link_to 'Show', schedule, class:"btn btn-success btn-xs" %> 
									<%= link_to 'Edit', edit_schedule_path(schedule), class:"btn btn-warning btn-xs" %> 
									<%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn 	btn-danger btn-xs" %></td>
								<% else %>

								<% end %>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<!-- ********************************* U13 ************************************************************* -->
<div class="panel panel-success">
	<div class="panel-heading">
		<h3 class="center division-heading"><strong><em>Boys U12</em></strong></h3>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th>Time</th>
						<th>Home</th>
						<th>Away</th>
					</tr>
				</thead>

				<tbody>
					<% @schedules.each do |schedule| %>
						<% if schedule.division_type == 'BU12' %>
							<tr>
								<td><%= schedule.gametime %></td>
								<td><%= schedule.hteam %></td>
								<td><%= schedule.ateam %></td>
								<% if schedule.user == current_user %>
									<td><%= link_to 'Show', schedule, class:"btn btn-success btn-xs" %> 
									<%= link_to 'Edit', edit_schedule_path(schedule), class:"btn btn-warning btn-xs" %> 
									<%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn 	btn-danger btn-xs" %></td>
								<% else %>

								<% end %>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<br>

<% if user_signed_in? %>
<%= link_to 'New Schedule', new_schedule_path, class:"btn btn-primary" %>
<% else %>

<% end %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game Time:</strong>
  <%= @schedule.gametime %>
</p>

<p>
  <strong>Home Team:</strong>
  <%= @schedule.hteam %>
</p>

<p>
  <strong>Away Team:</strong>
  <%= @schedule.ateam %>
</p>

<p>
  <strong>Division:</strong>
  <%= @schedule.division_type %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>